### ISSUE TITLE
Thoughts on what the color of the cards in the maps + guides section should represent? We have green, blue, and purple

### ISSUE THREAD

**Issue by asessums7** [ArberTu474/Visit-Dibra-website#106]

**Comment by ArberTu474** [comment]
we Have a list of these colors:
```
type color =
  | 'green'
  | 'orange'
  | 'yellow'
  | 'red'
  | 'purple'
  | 'blue'
  | 'dark-blue'
  | 'gray'
```
I can add more if we need. I saw the Begjunec video where you guys were putting yellow marks for the trail, so I thought we can add the colors of the trails.

**Comment by asessums7** [comment]
I meant more if the colors should coordinate or represent a certain type of trail. For example, green represents an easy trail etc. I think it's probably better to choose one color for all of the cards, rather than alternating colors.
