### ISSUE TITLE
Couple site clean-up tasks for Arber.

### ISSUE THREAD

**Issue by asessums7** [ArberTu474/Visit-Dibra-website#199]
- [x] 1. Switch Diber Tourism Center and Contact the Owner Directly cards. Contact the Owner Directly should be first then Tourist Information Center then Booking.com card.
- [x] 2. Send all "Learn More" button hrefs to the Blog section of the site.
- [x] 3. Confirm the contact form sends an email to the Diber TIC.

**Comment by ArberTu474** [comment]
For point 3. What is the Diber TIC email address?
